### ISSUE TITLE
imdbpy kann One Piece nicht Händeln

### ISSUE THREAD

**Issue by 9Mad-Max5** [rix1337/FeedCrawler#526]
# [FeedCrawler] Fehlermeldung
`Traceback (most recent call last):,
  File "/usr/lib/python3.6/site-packages/feedcrawler/crawler.py", line 126, in crawler,
    task.periodical_task(),
  File "/usr/lib/python3.6/site-packages/feedcrawler/sites/content_all_dw.py", line 79, in periodical_task,
    shared_blogs.periodical_task(self),
  File "/usr/lib/python3.6/site-packages/feedcrawler/sites/shared/content_all.py", line 885, in periodical_task,
    found = search_imdb(self, desired_rating, parsed_url),
  File "/usr/lib/python3.6/site-packages/feedcrawler/sites/shared/content_all.py", line 185, in search_imdb,
    if imdb_data.data["votes"] < 1500:,
KeyError: 'votes',
2021-08-31 07:54:30,232 CRITICAL [imdbpy] /usr/lib/python3.6/site-packages/imdb/_exceptions.py:34: IMDbDataAccessError exception raised; args: ({'errcode': None, 'errmsg': 'None', 'url': 'https://www.imdb.com/title/tt0388629/episodes?season=1', 'proxy': '', 'exception type': 'IOError', 'original exception': <HTTPError 400: ''>},); kwds: {},
Traceback (most recent call last):,
  File "/usr/lib/python3.6/site-packages/imdb/parser/http/__init__.py", line 220, in retrieve_unicode,
    response = uopener.open(url),
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open,
    response = meth(req, response),
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response,
    'http', request, response, code, msg, hdrs),
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error,
    return self._call_chain(*args),
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain,
    result = func(*args),
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default,
    raise HTTPError(req.full_url, code, msg, hdrs, fp),
urllib.error.HTTPError: HTTP Error 400: ,
2021-08-31 07:54:30,233 CRITICAL [imdbpy] /usr/lib/python3.6/site-packages/imdb/__init__.py:792: caught an exception retrieving or parsing "episodes" info set for mopID "0388629" (accessSystem: http),
Traceback (most recent call last):,
  File "/usr/lib/python3.6/site-packages/imdb/parser/http/__init__.py", line 220, in retrieve_unicode,
    response = uopener.open(url),
  File "/usr/lib/python3.6/urllib/request.py", line 532, in open,
    response = meth(req, response),
  File "/usr/lib/python3.6/urllib/request.py", line 642, in http_response,
    'http', request, response, code, msg, hdrs),
  File "/usr/lib/python3.6/urllib/request.py", line 570, in error,
    return self._call_chain(*args),
  File "/usr/lib/python3.6/urllib/request.py", line 504, in _call_chain,
    result = func(*args),
  File "/usr/lib/python3.6/urllib/request.py", line 650, in http_error_default,
    raise HTTPError(req.full_url, code, msg, hdrs, fp),
urllib.error.HTTPError: HTTP Error 400: ,
,
During handling of the above exception, another exception occurred:,
,
Traceback (most recent call last):,
  File "/usr/lib/python3.6/site-packages/imdb/__init__.py", line 787, in update,
    ret = method(mopID),
  File "/usr/lib/python3.6/site-packages/imdb/parser/http/__init__.py", line 631, in get_movie_episodes,
    self.urls['movie_main'] % movieID + 'episodes?season=' + str(season),
  File "/usr/lib/python3.6/site-packages/imdb/parser/http/__init__.py", line 378, in _retrieve,
    ret = self.urlOpener.retrieve_unicode(url, size=size),
  File "/usr/lib/python3.6/site-packages/imdb/parser/http/__init__.py", line 254, in retrieve_unicode,
    'original exception': e},
imdb._exceptions.IMDbDataAccessError: {'errcode': None, 'errmsg': 'None', 'url': 'https://www.imdb.com/title/tt0388629/episodes?season=1', 'proxy': '', 'exception type': 'IOError', 'original exception': <HTTPError 400: ''>},
[Ombi] - Fehler beim Abruf der IMDb für: 0388629,
`
**Ideen/Feature Requests** gehören in die [Discussions](https://github.com/rix1337/FeedCrawler/discussions/).

Für **Rückfragen** und Allgemeines gibt es den [Chat auf gitter](https://gitter.im/FeedCrawler/Lobby).

## Zwingend erforderlich

- **11.0.8**

- **frischer docker**

## Fehlerbeschreibung

Streng genommen ist es kein bug im FeedCrawler wenn ich das richtig sehe. Sondern viel mehr in IMDBpy. Allerdigns habe ich nicht alles zusammengesucht um dort ein gutes Issue zu machen.

Das hier ist die request Struktur:
https://www.imdb.com/title/**imdbid**/episodes?season=1

One Piece als Beispiel etwa liegt hier aber in folgender Form vor:
https://www.imdb.com/title/tt0388629/episodes?year=1999

Hier wird nach Jahren und nicht Seasons unterteilt was zu obigem Fehler führt.

**Comment by rix1337** [comment]
Korrekt. Das scheint ein Problem bei IMDBpy zu sein.
Das Team dort reagiert Recht schnell, mach also dort ein issue auf.

**Comment by rix1337** [comment]
https://github.com/alberanid/imdbpy/issues/330

**Comment by rix1337** [comment]
Im aktualisierten docker Image gefixt, auf Basis des Updates von imdbpy
