### ISSUE TITLE
.ini kaputt durch Änderung des Intervall in der WebUI

### ISSUE THREAD

**Issue by mx-hero** [rix1337/FeedCrawler#563]
# [FeedCrawler] Fehlermeldung

Dieser Bereich dient ausschließlich der Fehlermeldung.

**Ideen/Feature Requests** gehören in die [Discussions](https://github.com/rix1337/FeedCrawler/discussions/).

Für **Rückfragen** und Allgemeines gibt es den [Chat auf gitter](https://gitter.im/FeedCrawler/Lobby).

## Zwingend erforderlich

- **Fehlermeldung aus dem Log** (ggf. DEBUG aktivieren!)

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/lib/python3.6/site-packages/feedcrawler/web.py", line 97, in decorated
    config = CrawlerConfig('FeedCrawler')
  File "/usr/lib/python3.6/site-packages/feedcrawler/config.py", line 107, in __init__
    self._config.read(self._configfile)
  File "/usr/lib/python3.6/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/usr/lib/python3.6/configparser.py", line 1080, in _read
    raise MissingSectionHeaderError(fpname, lineno, line)
configparser.MissingSectionHeaderError: File contains no section headers.
file: '/config/FeedCrawler.ini', line: 1
'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x>
2021-12-20 09:00:12,246 - Exception on /img/favicon.ico [GET]
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib/python3.6/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/usr/lib/python3.6/site-packages/feedcrawler/web.py", line 97, in decorated
    config = CrawlerConfig('FeedCrawler')
  File "/usr/lib/python3.6/site-packages/feedcrawler/config.py", line 107, in __init__
    self._config.read(self._configfile)
  File "/usr/lib/python3.6/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/usr/lib/python3.6/configparser.py", line 1066, in _read
    lineno)
configparser.DuplicateSectionError: While reading from '/config/FeedCrawler.ini' [line 63]: section 'FeedCrawler' already e>

- **Genutzte Version** (kein Support für alte Releases)

12.0.4

## Fehlerbeschreibung

Ich habe in den Einstellungen den Intervall geändert, daraufhin hat er mir die halbe .ini zerschossen. Doppelte Einträge, Hoster weg, Alle Einstellungen unter Allgemein weg, etc. Habe die .ini per Hand wieder gefüllt und scheint wieder zu laufen.

**Comment by rix1337** [comment]
@mx-hero lad bitte noch deine ini Hoch, bei der der Fehler aufgetraten ist

**Comment by mx-hero** [comment]
Die originale mit der es aufgetreten ist, habe ich nicht mehr. Nur noch die, die ich per Hand wieder repariert habe. 

`[Hostnames]
sj =
dj =
sf = 
by =
fx = 
nk =
ww = 

[FeedCrawler]
auth_user =
auth_hash =
myjd_user = ****
myjd_pass = *****
myjd_device = *******
port = 9090
prefix =
interval = 20
flaresolverr = http://192.168.87.10:8191
flaresolverr_proxy =
english = False
surround =
closed_myjd_tab = False
one_mirror_policy = False
packages_per_myjd_page = 3

[Ombi]
url = http://172.17.0.10:3579
api = 80e6cc11bf99438d8c29e40f89f93c3d

[ContentAll]
quality = 1080p
search = 30
ignore = cam,subbed,xvid,dvdr,untouched,remux,avc,pal,md,ac3md,mic,xxx
regex = False
cutoff = True
enforcedl = False
crawlseasons = True
seasonsquality = 720p
seasonpacks = True
seasonssource = web-dl.*-(tvs|4sj|tvr)|webrip.*-(tvs|4sj|tvr)|webhd.*-(tvs|4sj|tvr)|netflix.*-(tvs|4sj|tvr)|amazon.*-(tvs|4>
imdbyear = 2010
imdb = 0.0
hevc_retail = True
retail_only = False
hoster_fallback = True

[ContentShows]
quality = 720p
rejectlist = xvid,subbed,hdtv
regex = False
hevc_retail = True
retail_only = False
hoster_fallback = False

[CustomDJ]
quality = 1080p
rejectlist = xvid,subbed
regex = False
hoster_fallback = False

[Crawljobs]
autostart = True
subdir = True

[Hosters]
rapidgator = True
turbobit = False
uploaded = False
zippyshare = False
oboom = False
ddl = True
filefactory = False
uptobox = False
1fichier = True
filer = True
nitroflare = False
ironfiles = False
k2s = False

[Notifications]
homeassistant =
pushbullet =
telegram = **********
pushover =`

**Comment by rix1337** [comment]
Hab versucht es mit deiner ini nachzustellen, was nicht gelungen ist.

Ergänz hier gerne Details, falls du es nochmal provoziert bekommst.
