### ISSUE TITLE
Ombianbindung führt zu Fehler

### ISSUE THREAD

**Issue by jankete** [rix1337/FeedCrawler#600]
# [FeedCrawler] Fehlermeldung

## Zwingend erforderlich

- **Fehlermeldung aus dem Log** (ggf. DEBUG aktivieren!)
`Erfolgreich mit Ombi verbunden.
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/feedcrawler/crawler.py", line 106, in crawler
    ombi_results = ombi(ombi_first_launch)
  File "/usr/lib/python3.9/site-packages/feedcrawler/ombi.py", line 99, in ombi
    best_result = feedcrawler.search.shared.content_all.get_best_result(title)
  File "/usr/lib/python3.9/site-packages/feedcrawler/search/shared/content_all.py", line 60, in get_best_result
    best_result = bl_results.get(best_match)
AttributeError: 'list' object has no attribute 'get'
Keine Prüfung für NK implementiert.
Erfolgreich mit Ombi verbunden.
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/feedcrawler/crawler.py", line 106, in crawler
    ombi_results = ombi(ombi_first_launch)
  File "/usr/lib/python3.9/site-packages/feedcrawler/ombi.py", line 99, in ombi
    best_result = feedcrawler.search.shared.content_all.get_best_result(title)
  File "/usr/lib/python3.9/site-packages/feedcrawler/search/shared/content_all.py", line 60, in get_best_result
    best_result = bl_results.get(best_match)
AttributeError: 'list' object has no attribute 'get'`

- **Genutzte Version** (kein Support für alte Releases)
13.0.1

- **Wird Python 3.9 oder aktueller genutzt?**
Docker-Container

## Fehlerbeschreibung

Beim Start des Crawlers wird eine Verbindung zu Ombi hergestellt. Danach kommt es zu einen Python-Fehler. Als Folge dessen dreht sich der Crawler im Kreis tun tritt eine Suche nach der anderen los.

**Comment by rix1337** [comment]
Danke für die aussagekräftige Meldung. Ist behoben.
