### ISSUE TITLE
Fehler im Log nach update auf 13.2.0

### ISSUE THREAD

**Issue by mx-hero** [rix1337/FeedCrawler#610]
# [FeedCrawler] Fehlermeldung

Das taucht nach dem Update plötzlich im Log auf. Der Crawler scheint dennoch ordnungsgemäß zu laufen. 

- **Fehlermeldung aus dem Log** (ggf. DEBUG aktivieren!)

File "/usr/lib/python3.9/urllib/request.py", line 561, in error

return self._call_chain(*args)
File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
result = func(*args)
File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404:

2022-04-14 20:45:35,360 CRITICAL [imdbpy] /usr/lib/python3.9/site-packages/imdb/__init__.py:833: caught an exception retrieving or parsing "episodes" info set for mopID "16492678" (accessSystem: http)
Traceback (most recent call last):
File "/usr/lib/python3.9/site-packages/imdb/parser/http/__init__.py", line 221, in retrieve_unicode
response = uopener.open(url)
File "/usr/lib/python3.9/urllib/request.py", line 523, in open
response = meth(req, response)
File "/usr/lib/python3.9/urllib/request.py", line 632, in http_response
response = self.parent.error(

File "/usr/lib/python3.9/urllib/request.py", line 561, in error

return self._call_chain(*args)
File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
result = func(*args)
File "/usr/lib/python3.9/urllib/request.py", line 641, in http_error_default
raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404:

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/usr/lib/python3.9/site-packages/imdb/__init__.py", line 831, in update
ret = method(mopID)
File "/usr/lib/python3.9/site-packages/imdb/parser/http/__init__.py", line 618, in get_movie_episodes
cont = self._retrieve(self.urls['movie_main'] % movieID + 'episodes')
File "/usr/lib/python3.9/site-packages/imdb/parser/http/__init__.py", line 379, in _retrieve
ret = self.urlOpener.retrieve_unicode(url, size=size)
File "/usr/lib/python3.9/site-packages/imdb/parser/http/__init__.py", line 249, in retrieve_unicode
raise IMDbDataAccessError(
imdb._exceptions.IMDbDataAccessError: {'errcode': None, 'errmsg': 'None', 'url': 'https://www.imdb.com/title/tt16492678/episodes', 'proxy': '', 'exception type': 'IOError', 'original exception': <HTTPError 404: ''>}
[Ombi] - Fehler beim Abruf der IMDb für: 16492678

- **Genutzte Version** (kein Support für alte Releases)

13.2.0

Docker / unRAID

**Comment by rix1337** [comment]
@mx-hero soweit ich das lesen kann, eine völlig normale Meldung, dass ein Link auf der IMDb nicht verfügbar ist.

Die Logeinträge stammen alle nur aus der cinemagoer Bibliothek. Hast du einen stacktrace der Zeit, von wo im Feedcrawler der Aufruf kommt? Sollte im Idealfall direkt davor im Log stehen

**Comment by mx-hero** [comment]
Das ist der Rest den ich da raus ziehen konnte auf die schnelle.
[feedcrawler_log.txt](https://github.com/rix1337/FeedCrawler/files/8495446/feedcrawler_log.txt)

**Comment by rix1337** [comment]
Lösungsansatz: Cinemagoer (aka IMDBpy) wieder vollständig entfernen.
So können auch ein paar transitive Abhängigkeiten entfernt und damit die Installation verschlankt werden.

**Comment by rix1337** [comment]
Die Fehlermeldungen sind übrigens völlig berechtigt. Ombi behauptet, der Film sei eine Serie. Daher versucht der crawler dessen Episoden abzurufen und scheitert. 
Episoden gibt's schließlich keine ;)
