### ISSUE TITLE
Diverse Fehler in v14

### ISSUE THREAD

**Issue by jankete** [rix1337/FeedCrawler#614]
# [FeedCrawler] Fehlermeldung

## Zwingend erforderlich

- **Fehlermeldung aus dem Log** (ggf. DEBUG aktivieren!)
```[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 01-envfile: executing... 
[cont-init.d] 01-envfile: exited 0.
[cont-init.d] 01-migrations: executing... 
[migrations] started
[migrations] no migrations found
[cont-init.d] 01-migrations: exited 0.
[cont-init.d] 02-tamper-check: executing... 
[cont-init.d] 02-tamper-check: exited 0.
[cont-init.d] 10-adduser: executing... 
[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 90-custom-folders: executing... 
[cont-init.d] 90-custom-folders: exited 0.
[cont-init.d] 99-custom-files: executing... 
[custom-init] no custom files found exiting...
[cont-init.d] 99-custom-files: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.
┌──────────────────────────────────────────────┐
  FeedCrawler v.14.0.0 von RiX
  https://github.com/rix1337/FeedCrawler
└──────────────────────────────────────────────┘
Nutze das Verzeichnis /config für Einstellungen/Logs
Hostname für SJ: *******
Hostname für DJ: Nicht gesetzt!
Hostname für SF: *******
Hostname für BY: Nicht gesetzt!
Hostname für FX: Nicht gesetzt!
Hostname für FF: *******
Traceback (most recent call last):
  File "/usr/bin/feedcrawler", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.9/site-packages/feedcrawler/main.py", line 110, in main
    if not get_device():
  File "/usr/lib/python3.9/site-packages/feedcrawler/myjd.py", line 60, in get_device
Hostname für HW: *******
Hostname für NK: *******
Hostname für WW: Nicht gesetzt!
Hostname für DD: Nicht gesetzt!
    device = jd.get_device(myjd_device)
  File "/usr/lib/python3.9/site-packages/feedcrawler/myjdapi.py", line 1023, in get_device
    return Jddevice(self, device)
  File "/usr/lib/python3.9/site-packages/feedcrawler/myjdapi.py", line 692, in __init__
    self.__refresh_direct_connections()
  File "/usr/lib/python3.9/site-packages/feedcrawler/myjdapi.py", line 698, in __refresh_direct_connections
    response = self.myjd.request_api("/device/getDirectConnectionInfos",
  File "/usr/lib/python3.9/site-packages/feedcrawler/myjdapi.py", line 1099, in request_api
    encrypted_response = request(
  File "/usr/lib/python3.9/site-packages/feedcrawler/http_handlers/requests.py", line 132, in request
    with opener.open(req, timeout=timeout) as resp:
  File "/usr/lib/python3.9/urllib/request.py", line 517, in open
    response = self._open(req, data)
  File "/usr/lib/python3.9/urllib/request.py", line 534, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/usr/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/lib/python3.9/urllib/request.py", line 1389, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/usr/lib/python3.9/urllib/request.py", line 1350, in do_open
    r = h.getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1371, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 319, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 280, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out
┌──────────────────────────────────────────────┐
  FeedCrawler v.14.0.0 von RiX
  https://github.com/rix1337/FeedCrawler
└──────────────────────────────────────────────┘
Nutze das Verzeichnis /config für Einstellungen/Logs
Hostname für SJ: *******
Hostname für DJ: Nicht gesetzt!
Hostname für SF: *******
Hostname für BY: Nicht gesetzt!
Hostname für FX: Nicht gesetzt!
Hostname für FF: *******
Hostname für HW: *******
Hostname für NK: *******
Hostname für WW: Nicht gesetzt!
Hostname für DD: Nicht gesetzt!
Erfolgreich mit My JDownloader verbunden. Gerätename: *******
Keine Prüfung für NK implementiert.
Fehler beim Abruf von: https://SF/api/v2/search?q=Obi-Wan Kenobi&ql=DE URL can't contain control characters. '/api/v2/search?q=Obi-Wan Kenobi&ql=DE' (found at least ' ')
Fehler beim Abruf von: https://*******/api/v2/search?q=Obi-Wan Kenobi&ql=DE URL can't contain control characters. '/api/v2/search?q=Obi-Wan Kenobi&ql=DE' (found at least ' ')
Fehler beim Abruf von: https://*******/api/v2/search?q=Obi-Wan Kenobi&ql=DE URL can't contain control characters. '/api/v2/search?q=Obi-Wan Kenobi&ql=DE' (found at least ' ')
Fehler beim Abruf von: https://*******/api/v2/search?q=Obi-Wan Kenobi&ql=DE URL can't contain control characters. '/api/v2/search?q=Obi-Wan Kenobi&ql=DE' (found at least ' ')
Fehler beim Abruf von: https://*******/api/v2/search?q=Obi-Wan Kenobi&ql=DE URL can't contain control characters. '/api/v2/search?q=Obi-Wan Kenobi&ql=DE' (found at least ' ')
Serie/Staffel/Episode: Obi-Wan Kenobi durch Ombi hinzugefügt.
2022-04-26 05:31:15 - Alle Suchläufe ausgeführt (Dauer: 00:00:54)!
2022-04-26 05:31:15 - Die Ombi-Suche lief für: 13 Filme und 1 Serien
-----------Wartezeit bis zum nächsten Suchlauf: 04:12:15-----------```

- **Genutzte Version** (kein Support für alte Releases)
v.14.0.0

- **Wird Python 3.9 oder aktueller genutzt?**
Docker-Container

## Fehlerbeschreibung

Beim Starten des Containers kommt es zu den o.g. Fehlern auf der Docker-Console.

**Comment by jankete** [comment]
Der Helper hat mit der neuen Version auch so seine Probleme

![Screenshot_20220426-185840](https://user-images.githubusercontent.com/22338766/165353733-103595f3-65cd-4421-82af-d4fa8be30485.png)

**Comment by jankete** [comment]
Der Helper hat mit der neuen Version auch so seine Probleme

![Screenshot_20220426-185840~2](https://user-images.githubusercontent.com/22338766/165353948-0dc3421d-137d-48da-85f5-2f5690e6a767.png)

**Comment by jankete** [comment]
Ich habe den Container jetzt nochmal neu aufgebaut und gestartet. Die Python-Fehler sind nun weg, die "URL can't contain control characters." Meldungen bleiben.
