### ISSUE TITLE
JDownloader Update funktioniert nicht mehr 

### ISSUE THREAD

**Issue by jankete** [rix1337/FeedCrawler#670]
# [FeedCrawler] Fehlermeldung

Dieser Bereich dient ausschließlich der Fehlermeldung.

**Ideen/Feature Requests** gehören in die [Discussions](https://github.com/rix1337/FeedCrawler/discussions/).

Für **Rückfragen** und Allgemeines gibt es den [Chat auf gitter](https://gitter.im/FeedCrawler/community).

## Zwingend erforderlich

- **Fehlermeldung aus dem Log** (ggf. DEBUG aktivieren!)
```Erfolgreich mit My JDownloader verbunden. Gerätename: xxxxxx
2022-12-08 13:12:15 - Alle Suchläufe ausgeführt (Dauer: 00:06:56)!
2022-12-08 13:12:15 - Die Ombi-Suche lief für: 7 Filme
-----------Wartezeit bis zum nächsten Suchlauf: 04:39:13-----------
JDownloader Update steht bereit und JDownloader ist inaktiv.
Führe Update durch und starte JDownloader neu...
Fehler bei Aufruf von: https://api.jdownloader.org/t_5b353699d348b817880b05064a93b7bed8320e6b_197f44766e9f18d1e312739c303d07f2/downloadcontroller/getCurrentState (The read operation timed out, timeout=30s)
Fehler bei Aufruf von: https://api.jdownloader.org/t_5b353699d348b817880b05064a93b7bed8320e6b_197f44766e9f18d1e312739c303d07f2/device/getDirectConnectionInfos (The read operation timed out, timeout=30s)
Process Process-2:
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.9/site-packages/feedcrawler/jobs/feed_search.py", line 216, in crawler
    jdownloader_update()
  File "/usr/lib/python3.9/site-packages/feedcrawler/providers/myjd_connection.py", line 730, in jdownloader_update
    shared_state.device.update.restart_and_update()
  File "/usr/lib/python3.9/site-packages/feedcrawler/external_tools/myjd_api.py", line 140, in restart_and_update
    resp = self.device.action(self.url + "/restartAndUpdate")
  File "/usr/lib/python3.9/site-packages/feedcrawler/external_tools/myjd_api.py", line 832, in action
    self.__refresh_direct_connections()
  File "/usr/lib/python3.9/site-packages/feedcrawler/external_tools/myjd_api.py", line 771, in __refresh_direct_connections
    response = self.myjd.request_api("/device/getDirectConnectionInfos",
  File "/usr/lib/python3.9/site-packages/feedcrawler/external_tools/myjd_api.py", line 1204, in request_api
    raise RequestTimeoutException
feedcrawler.external_tools.myjd_api.RequestTimeoutException
```

- **Genutzte Version** (kein Support für alte Releases)
16.0.0

- **Wird Python 3.6 oder aktueller genutzt?**
aktueller Docker Container

## Fehlerbeschreibung
Nach dem Suchlauf wird versucht, wie gewünscht, den JDownloader zu aktualisieren. Die klappt aber nicht und führt zu o.g. Fehlermeldung. Nachfolgende Suchläufe werden dann nicht mehr gestartet.

**Comment by rix1337** [comment]
Sicher, dass der JDownloader nicht neustartet? Die Fehlermeldung sagt nur, dass der JDownloader kurzfristig nicht erreichbar war. Und das ist während eines Updates absolut erwartbar.

**Comment by rix1337** [comment]
Funktioniert die Steuerung vom JDownloader und den Paketen?

Laut Fehlermeldung läuft
- Deine Verbindung über die JDownloader api, statt über die lokale IP direkt zum JDownloader
- Die Verbindung sehr langsam (Timeout nach 30 Sekunden)

**Comment by jankete** [comment]
Da muss ist erstmal etwas laden. Ich schaue mir das an und melde mich.

**Comment by jankete** [comment]
Ich habe im JDownloader jetzt "Allow direct connections from LAN" aktiviert. Jetzt funktioniert die Update-Routine über den Crawler wieder.

**Comment by rix1337** [comment]
Sehr gut zu wissen. Scheinbar sind die Verbindungen über deren Server teils zu langsam
