### ISSUE TITLE
DW Broken Pipe im Suchlauf

### ISSUE THREAD

**Issue by 9Mad-Max5** [rix1337/FeedCrawler#738]
### Hast du die README gelesen?

- [X] Ich habe die README gelesen

### Gibt es bereits ein Issue für das Problembild?

- [X] Ich habe ältere, offene und geschlossene Issues überprüft

### Hast du die Discussions überprüft?

- [X] Ich habe die Diskussionen gelesen

### Enthält die Problembeschreibung einen oder mehrere Hostnamen?

- [X] Nein, ich habe keine Hostnamen in der Problembeschreibung hinterlegt.

### Laufzeitumgebung

```markdown
- FeedCrawler Version: 18.0.4
- Letzte funktionierende FeedCrawler-Version: 18.0.1
- Betriebssystem: docker
- Docker: [ja]
- Sponsors-Helper-URL: [ja]
- FlareSolverr-URL: [ja]
```

### Beschreibung

Nach einer Weile bricht die Suche ab und ich bekomme die broken Pipe Meldung.
Sehe aktuell nicht, wo der Grund ist. Auch löschen der DB und mehrmaliges neu aufsetzten des Containers ändern nichts.

### Fehlermeldungen aus dem Log

```text
-----------Suchlauf (DW - Liste: List_ContentAll_Movies) gestartet!-----------
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/feedcrawler/jobs/package_watcher.py", line 50, in watch_packages
    myjd_packages = get_info()
  File "/usr/lib/python3.9/site-packages/feedcrawler/providers/myjd_connection.py", line 383, in get_info
    if not shared_state.get_device():
  File "/usr/lib/python3.9/site-packages/feedcrawler/providers/shared_state.py", line 143, in get_device
    return values["device"]
  File "<string>", line 2, in __getitem__
  File "/usr/lib/python3.9/multiprocessing/managers.py", line 809, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/managers.py", line 802, in _callmethod
    conn = self._tls.connection
AttributeError: 'ForkAwareLocal' object has no attribute 'connection'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/bin/bottle.py", line 876, in _handle
    return route.call(**args)
  File "/usr/bin/bottle.py", line 1759, in wrapper
    rv = callback(*a, **ka)
  File "/usr/lib/python3.9/site-packages/feedcrawler/web_interface/web_server.py", line 137, in wrapper
    _config = CrawlerConfig('FeedCrawler')
  File "/usr/lib/python3.9/site-packages/feedcrawler/providers/config.py", line 141, in __init__
    self._configfile = shared_state.values["configfile"]
  File "<string>", line 2, in __getitem__
  File "/usr/lib/python3.9/multiprocessing/managers.py", line 806, in _callmethod
    self._connect()
  File "/usr/lib/python3.9/multiprocessing/managers.py", line 793, in _connect
    conn = self._Client(self._token.address, authkey=self._authkey)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 502, in Client
    c = SocketClient(address)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 630, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused
Fehler beim Abruf von: https://DW/page/9/?s [Errno 32] Broken pipe
Fehler bei der Feed-Suche: [Errno 32] Broken pipe
-----------Suchlauf (DW - Liste: List_ContentAll_Movies) ausgeführt!-----------
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/feedcrawler/jobs/feed_search.py", line 189, in feed_crawler
    if FeedDb('site_status').retrieve(name + "_normal"):
  File "/usr/lib/python3.9/site-packages/feedcrawler/providers/sqlite_database.py", line 63, in __init__
    self._conn = sqlite3.connect(shared_state.values["dbfile"], check_same_thread=False, timeout=5)
  File "<string>", line 2, in __getitem__
  File "/usr/lib/python3.9/multiprocessing/managers.py", line 809, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
```

### FeedCrawler.ini

```text
[FeedCrawler]
auth_user =
auth_hash =
myjd_user = piloader411@protonmail.com
myjd_pass = xx
myjd_device = nas
port = 9090
prefix =
interval = 20
flaresolverr = http://192.168.4.22:8191
english = False
surround = False
one_mirror_policy = True
packages_per_myjd_page = 5
myjd_auto_update = False
force_ignore_in_web_search = False
sponsors_helper = http://192.168.4.22:9700

[Hostnames]
dj = secret|j734hwG51SK3NFL/9wxb2Q==
fx = secret|e+wq8/z2f3QOgFRWuxV2kQ==
nk = secret|5Q79gHGBBuPnf4fSm0uUIg==
dd = secret|Nxe0DgwF5TImjhJZkUgk3JE1n1PgMqtiyWh1tvXr8FM=
sf = secret|8rz0UwwwV4fzDrKIbDUj6Q==
dw = secret|XhEumzzy6H7jEYE2R0tSmw==

[Hosters]
rapidgator = True
turbobit = False
ddl = True
filefactory = False
uptobox = False
1fichier = False
filer = True
nitroflare = False
ironfiles = False
k2s = False
katfile = False

[Notifications]
homeassistant =
pushbullet =
telegram = xxx
pushover =
discord =

[Ombi]
url = http://192.168.4.22:3579
api = xx

[Crawljobs]
autostart = True
subdir = True
subdir_by_type = False

[ContentAll]
quality = 1080p
search = 30
ignore = cam,subbed,xvid,dvdr,untouched,remux,avc,pal,md,ac3md,mic,xxx,aacmd
regex = True
cutoff = True
enforcedl = False
crawlseasons = True
seasonsquality = 1080p
seasonpacks = True
seasonssource = hdtv|hdtvrip|tvrip|web|web-dl|webrip|webhd|netflix*|amazon*|itunes*|bluray|bd|bdrip
imdbyear = 2010
imdb = 8.1
hevc_retail = False
retail_only = False
hoster_fallback = False

[ContentShows]
quality = 1080p
rejectlist = xvid,subbed,hdtv
regex = False
hevc_retail = True
retail_only = False
hoster_fallback = False

[CustomDJ]
quality = 1080p
rejectlist = xvid,subbed
regex = False
hoster_fallback = False

[CustomDD]
hoster_fallback = False

[CustomF]
search = 3

[Overseerr]
url =
api =

[SponsorsHelper]
max_attempts = 3
hide_donation_banner = True

[Plex]
url = xx
api = xx
client_id = xx
pin_code =
pin_id =

[Cloudflare]
wait_time = 12
```

**Comment by rix1337** [comment]
The specific error message in the first section of the traceback is a "BrokenPipeError" caused by a "Broken pipe". This error typically occurs when a program tries to write to a connection that has been closed by the other end, which could be caused by a network issue, a bug in the code, or some other system issue.

The second section of the traceback is an "AttributeError" caused by an object not having an expected attribute. This suggests that there may be an issue with how objects are being passed between different parts of the program.

The third section of the traceback is a "ConnectionRefusedError" indicating that the program was not able to connect to a specified address, which may be due to a network issue or an incorrect address.

Overall, the traceback suggests that there may be some issues with network connections, object passing, or other system-related issues that are causing the program to fail.


Tritt das Problem nur mit DW auf?  Könnte ein Netzwerkproblem sein.
Probier bitte mindestens 2 alternative Hostnamen aus, die den selben Scope durchsuchen. FX, FF, o. Ä.

**Comment by rix1337** [comment]
@9Mad-Max5 alternativ kann es an der internen Kommunikation

```
It's possible that the multiprocessing module is attempting to use networking internally for inter-process communication, even if the processes are running on the same machine. For example, the multiprocessing module can use pipes or sockets to communicate between processes, which technically involves network protocols.

One possible cause of the BrokenPipeError and ConnectionRefusedError exceptions you're seeing is a failure in the underlying communication mechanism used by multiprocessing. This could be due to network issues (e.g. firewall blocking traffic), system resource constraints (e.g. insufficient memory or CPU), or other factors.
```

**Comment by rix1337** [comment]
Am wahrscheinlichsten kommt das Problem durch gleichzeitige Änderungen am device zustande.

Lösungsansatz: lock

```
import multiprocessing

def worker(lock, shared_dict):
    while True:
        # acquire the lock
        lock.acquire()
        try:
            # modify the shared dict
            shared_dict['key'] += 1
        finally:
            # release the lock
            lock.release()

if __name__ == '__main__':
    # create a manager dict
    manager = multiprocessing.Manager()
    shared_dict = manager.dict({'key': 0})
    
    # create a lock object
    lock = manager.Lock()
    
    # create four worker processes
    processes = []
    for i in range(4):
        p = multiprocessing.Process(target=worker, args=(lock, shared_dict))
        p.start()
        processes.append(p)
```

Before modifying the shared dict, the process acquires the lock using the lock.acquire() method. This will block the process if another process already holds the lock. Once the lock is acquired, the process modifies the shared dict and then releases the lock using the lock.release() method.

Das lock wird vermutlich überall gebraucht, wo Werte des Shared dict verändert werden.
Das lesen von Werten ist hiervon nicht betroffen.

**Comment by 9Mad-Max5** [comment]
Es gilt nach meiner Kenntniss als essenziel mit Locks zu arbeiten beim multiprocessing/multithreading. Hast du eine Idee wo ich es fixen kann?

**Comment by rix1337** [comment]
Dachte manager.dict kümmert sich da selber drum.

Todo um ein lock einzubauen:
1. In crawler.py neben dem manager_dict auch ein lock erzeugen
2. Das lock in jeden Prozess übergeben (analog zum dict)
3. Global variable "lock" in shared state ergänzen, setter (analog dict) implementieten
4. Von jedem Prozess aus "lock" in shared state auf das selbe lock setzen (aus Schritt 1 und 2)
5. Alle Codestellen die Werte im shared state dict setzen (also values[bla] = foo) in eine helper Funktion auslagern, die das lock per try/finally setzt

Das auslesen des dict aus shared state benötigt kein lock. Die helper Funktion wird vmtl. so aussehen:

def set_value(key, value)
global lock

**Comment by 9Mad-Max5** [comment]
Puhh das ist ja eine ganze Menge was angefasst werden muss.
Schade das du dann erst drann kommst. Aktuell braket es den kompletten crawler und ich Laufe in Error 500.
