### ISSUE TITLE
DW still leads to Broken Pipe

### ISSUE THREAD

**Issue by 9Mad-Max5** [rix1337/FeedCrawler#742]
### Hast du die README gelesen?

- [X] Ich habe die README gelesen

### Gibt es bereits ein Issue für das Problembild?

- [X] Ich habe ältere, offene und geschlossene Issues überprüft

### Hast du die Discussions überprüft?

- [X] Ich habe die Diskussionen gelesen

### Enthält die Problembeschreibung einen oder mehrere Hostnamen?

- [X] Nein, ich habe keine Hostnamen in der Problembeschreibung hinterlegt.

### Laufzeitumgebung

```markdown
- FeedCrawler Version:18.1.0
- Letzte funktionierende FeedCrawler-Version:18.0.x
- Betriebssystem: unix
- Docker: [ja]
- Sponsors-Helper-URL: [ja]
- FlareSolverr-URL: [ja]
```

### Beschreibung

Servus,

Bei DW kommt es nach wie vor noch zu dem Broken Pipe fehler.
Hier sieht man mal den Anfang der Meldung aber bin mir auch nicht sicher woher das problem kommt

### Fehlermeldungen aus dem Log

```text
Fehler beim Abruf von: https://dw.cc/video/scene/eine-bahre-fuer-den-sheriff-1965-german-web-h264-dunghill/ [Errno 104] Connection reset by peer
DW hat den Feed angepasst. Parsen teilweise nicht möglich!
Fehler bei der Feed-Suche: [Errno 32] Broken pipe
-----------Suchlauf (DW - Liste: IMDb) ausgeführt!-----------
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/feedcrawler/jobs/feed_search.py", line 189, in feed_crawler
    if FeedDb('site_status').retrieve(name + "_normal"):
  File "/usr/lib/python3.9/site-packages/feedcrawler/providers/sqlite_database.py", line 63, in __init__
    self._conn = sqlite3.connect(shared_state.values["dbfile"], check_same_thread=False, timeout=5)
  File "<string>", line 2, in __getitem__
  File "/usr/lib/python3.9/multiprocessing/managers.py", line 809, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/feedcrawler/jobs/feed_search.py", line 107, in feed_crawler
    if not shared_state.values["test_run"]:
  File "<string>", line 2, in __getitem__
  File "/usr/lib/python3.9/multiprocessing/managers.py", line 809, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/feedcrawler/jobs/package_watcher.py", line 47, in watch_packages
    if not shared_state.get_device():
  File "/usr/lib/python3.9/site-packages/feedcrawler/providers/shared_state.py", line 135, in get_device
    if check_device(values["device"]):
  File "<string>", line 2, in __getitem__
  File "/usr/lib/python3.9/multiprocessing/managers.py", line 809, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/managers.py", line 802, in _callmethod
    conn = self._tls.connection
AttributeError: 'ForkAwareLocal' object has no attribute 'connection'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/bin/bottle.py", line 876, in _handle
    return route.call(**args)
  File "/usr/bin/bottle.py", line 1759, in wrapper
    rv = callback(*a, **ka)
  File "/usr/lib/python3.9/site-packages/feedcrawler/web_interface/web_server.py", line 137, in wrapper
    _config = CrawlerConfig('FeedCrawler')
  File "/usr/lib/python3.9/site-packages/feedcrawler/providers/config.py", line 141, in __init__
    self._configfile = shared_state.values["configfile"]
  File "<string>", line 2, in __getitem__
  File "/usr/lib/python3.9/multiprocessing/managers.py", line 806, in _callmethod
    self._connect()
  File "/usr/lib/python3.9/multiprocessing/managers.py", line 793, in _connect
    conn = self._Client(self._token.address, authkey=self._authkey)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 502, in Client
    c = SocketClient(address)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 630, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/managers.py", line 802, in _callmethod
    conn = self._tls.connection
AttributeError: 'ForkAwareLocal' object has no attribute 'connection'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/bin/bottle.py", line 876, in _handle
    return route.call(**args)
  File "/usr/bin/bottle.py", line 1759, in wrapper
    rv = callback(*a, **ka)
  File "/usr/lib/python3.9/site-packages/feedcrawler/web_interface/web_server.py", line 137, in wrapper
    _config = CrawlerConfig('FeedCrawler')
  File "/usr/lib/python3.9/site-packages/feedcrawler/providers/config.py", line 141, in __init__
    self._configfile = shared_state.values["configfile"]
  File "<string>", line 2, in __getitem__
  File "/usr/lib/python3.9/multiprocessing/managers.py", line 806, in _callmethod
    self._connect()
  File "/usr/lib/python3.9/multiprocessing/managers.py", line 793, in _connect
    conn = self._Client(self._token.address, authkey=self._authkey)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 502, in Client
    c = SocketClient(address)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 630, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/usr/lib/python3.9/multiprocessing/managers.py", line 802, in _callmethod
    conn = self._tls.connection
AttributeError: 'ForkAwareLocal' object has no attribute 'connection'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/bin/bottle.py", line 876, in _handle
    return route.call(**args)
  File "/usr/bin/bottle.py", line 1759, in wrapper
    rv = callback(*a, **ka)
  File "/usr/lib/python3.9/site-packages/feedcrawler/web_interface/web_server.py", line 137, in wrapper
    _config = CrawlerConfig('FeedCrawler')
  File "/usr/lib/python3.9/site-packages/feedcrawler/providers/config.py", line 141, in __init__
    self._configfile = shared_state.values["configfile"]
  File "<string>", line 2, in __getitem__
  File "/usr/lib/python3.9/multiprocessing/managers.py", line 806, in _callmethod
    self._connect()
  File "/usr/lib/python3.9/multiprocessing/managers.py", line 793, in _connect
    conn = self._Client(self._token.address, authkey=self._authkey)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 502, in Client
    c = SocketClient(address)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 630, in SocketClient
    s.connect(address)
ConnectionRefusedError: [Errno 111] Connection refused
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/feedcrawler/jobs/feed_search.py", line 107, in feed_crawler
    if not shared_state.values["test_run"]:
  File "<string>", line 2, in __getitem__
  File "/usr/lib/python3.9/multiprocessing/managers.py", line 809, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
BrokenPipeError: [Errno 32] Broken pipe
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/feedcrawler/jobs/feed_search.py", line 107, in feed_crawler
    if not shared_state.values["test_run"]:
  File "<string>", line 2, in __getitem__
  File "/usr/lib/python3.9/multiprocessing/managers.py", line 809, in _callmethod
    conn.send((self._id, methodname, args, kwds))
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 411, in _send_bytes
    self._send(header + buf)
  File "/usr/lib/python3.9/multiprocessing/connection.py", line 368, in _send
    n = write(self._handle, buf)
```

### FeedCrawler.ini

```text
[FeedCrawler]
auth_user = 
auth_hash = 
myjd_user = secret|VVbnUCk33pNPdGpzrBbYuvMjfvoSQk/8YoU+gv+fRwk=
myjd_pass = secret|s/CWVGT67aJ6W56S9t54iAdzHWlur+/30/IBpTpHguI=
myjd_device = nas
port = 9090
prefix = 
interval = 20
flaresolverr = http://172.10.30.25:8191
english = False
surround = False
one_mirror_policy = True
packages_per_myjd_page = 5
myjd_auto_update = False
force_ignore_in_web_search = False
sponsors_helper = http://172.10.30.22:9700

[Hostnames]
dw = secret|XhEumzzy6H7jEYE2R0tSmw==
sj = secret|zaf6Th3oeu188ZOHckgLG15HcglhaUOPR5NhBqIVoWk=
dj = secret|j734hwG51SK3NFL/9wxb2Q==
sf = secret|8rz0UwwwV4fzDrKIbDUj6Q==
fx = secret|e+wq8/z2f3QOgFRWuxV2kQ==
nk = secret|5Q79gHGBBuPnf4fSm0uUIg==
ww = secret|8sRNCcZy846CMBh5otaWQg==

[Hosters]
rapidgator = True
turbobit = False
ddl = True
filefactory = False
uptobox = False
1fichier = False
filer = True
nitroflare = False
ironfiles = False
k2s = False
katfile = False

[Notifications]
homeassistant = 
pushbullet = 
telegram = 
pushover = 
discord = 

[Ombi]
url = http://172.10.30.20:3579
api = secret|1+vu480pgC220dTXSG7mcqJOMBFHC+Gc+PUcgzzaSkb2GLZhEAJcgwkbGOtl9SzU

[Crawljobs]
autostart = True
subdir = True
subdir_by_type = False

[ContentAll]
quality = 1080p
search = 30
ignore = cam,subbed,xvid,dvdr,untouched,remux,avc,pal,md,ac3md,mic,xxx,aacmd
regex = False
cutoff = True
enforcedl = False
crawlseasons = True
seasonsquality = 1080p
seasonpacks = True
seasonssource = hdtv|hdtvrip|tvrip|web|web-dl|webrip|webhd|netflix*|amazon*|itunes*|bluray|bd|bdrip
imdbyear = 2010
imdb = 8.1
hevc_retail = True
retail_only = False
hoster_fallback = False

[ContentShows]
quality = 1080p
rejectlist = xvid,subbed,hdtv
regex = False
hevc_retail = True
retail_only = False
hoster_fallback = False

[CustomDJ]
quality = 1080p
rejectlist = xvid,subbed
regex = False
hoster_fallback = False

[CustomDD]
hoster_fallback = False

[CustomF]
search = 3

[Overseerr]
url = 
api = 

[SponsorsHelper]
max_attempts = 3
hide_donation_banner = True

[Plex]
url = https://46-142-178-30.ccbe912b126642519a5d5af47cd7a492.plex.direct:32400
api = secret|c40lwP3RcVVKJ2Drt0IM5UNg0rMoFn+VV2TeKV3m3kQ=
client_id = secret|F3w/xHh0uMzPFmMQZQmxnw==
pin_code = 
pin_id = 

[Cloudflare]
wait_time = 12
```

**Comment by rix1337** [comment]
Fehlermeldung ist seit 3 Tagen inaktiv. Bitte innerhalb eines Tages aktualisieren oder kommentieren, sonst wird diese geschlossen.

**Comment by 9Mad-Max5** [comment]
Ich habe es auch nicht wieder reproduzieren können aktuell also schließe ich mal. Muss aber dazu sagen das ich DD mal aus der Liste der Hoster genommen habe da mir die weg vom Fenster scheinen
